cmake_minimum_required(VERSION 3.22)
project(click_meow LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_AUTOMOC ON)
find_package(Qt6 REQUIRED COMPONENTS Widgets Multimedia DBus Qml Quick)
find_package(PkgConfig REQUIRED)
pkg_check_modules(KDE REQUIRED IMPORTED_TARGET KF6CoreAddons KF6WindowSystem epoxy wayland-server libdrm)
find_package(KF6Config REQUIRED)
find_path(KWIN_INCLUDE_DIR effect/effecthandler.h PATH_SUFFIXES kwin REQUIRED)
find_library(KWIN_LIBRARY kwin REQUIRED)
add_library(meowbridge MODULE bridge.cpp)
target_include_directories(meowbridge PRIVATE ${KWIN_INCLUDE_DIR})
target_link_libraries(meowbridge PRIVATE ${KWIN_LIBRARY} Qt6::Quick Qt6::Widgets Qt6::DBus KF6::ConfigCore PkgConfig::KDE)
set_target_properties(meowbridge PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/effect/contents/ui/MeowBridge")
add_executable(click-meow main.cpp)
target_link_libraries(click-meow PRIVATE Qt6::Widgets Qt6::Multimedia Qt6::DBus)
target_compile_definitions(click-meow PRIVATE
    MEOW_ROOT="${CMAKE_SOURCE_DIR}"
    MEOW_DESKTOP_PATH="${CMAKE_CURRENT_BINARY_DIR}/click-meow.desktop")
configure_file(click-meow.desktop.in click-meow.desktop @ONLY)
